In [17]:
pip install --upgrade tensorflow


In [18]:


import keras
import tensorflow as tf

print("Keras version:", keras.__version__)
print("TensorFlow version:", tf.__version__)

frases =['Hola mundo',
         'Hola a todos',
         'Hola a todo el mundo']





Keras version: 3.4.1
TensorFlow version: 2.17.0


In [21]:

#no sirven, toco hacerlo con tensorflow
#from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index=', word_index)



word_index= {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


In [28]:
#generacion secuencia de tokenizadas

secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias=', secuencias)



secuencias= [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


In [29]:
#rellena las secuencias a una longitud uniforme

relleno= keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)

rellena =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


In [34]:
import keras
import tensorflow as tf

frases =['Hola mundo',
         'Hola a todos',
         'Hola a todo el mundo',
         'Buen dia, como estas hoy']

#no sirven, toco hacerlo con tensorflow
#from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index=', word_index)

#generacion secuencia de tokenizadas

secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias=', secuencias)

#rellena las secuencias a una longitud uniforme

relleno= keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)



word_index= {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'buen': 7, 'dia': 8, 'como': 9, 'estas': 10, 'hoy': 11}
secuencias= [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]
rellena =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


In [35]:
import keras
import tensorflow as tf

frases =['Hola mundo',
         'Hola a todos',
         'Hola a todo el mundo',
         'Buen dia, como estas hoy']

#no sirven, toco hacerlo con tensorflow
#from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index=', word_index)

#generacion secuencia de tokenizadas

secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias=', secuencias)

#rellena las secuencias a una longitud uniforme

relleno= keras.preprocessing.sequence.pad_sequences(secuencias)
print('rellena =\n', relleno)


word_index= {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'dia': 9, 'como': 10, 'estas': 11, 'hoy': 12}
secuencias= [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
rellena =
 [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


In [38]:
import keras
import tensorflow as tf

frases =['Hola mundo',
         'Hola a todos',
         'Hola a todo el mundo',
         'Buen dia, como estas hoy']

#no sirven, toco hacerlo con tensorflow
#from keras.preprocessing.text import Tokenizer
#from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

# Genera el diccionario de tokens
tokenizer = Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index=', word_index)

#generacion secuencia de tokenizadas

secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias=', secuencias)


#rellena las secuencias a una longitud uniforme

relleno= keras.preprocessing.sequence.pad_sequences(secuencias,padding='post',truncating='post')
print('rellena =\n', relleno)


word_index= {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'dia': 9, 'como': 10, 'estas': 11, 'hoy': 12}
secuencias= [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
rellena =
 [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
