In [3]:
import numpy as np

# Definir las señales de entrada y el filtro
x = np.array([2, 1, 0, 1, 2])
h = np.array([1, -1])

# Realizar la convolución
y = np.convolve(x, h, mode='valid')



In [4]:
# Imprimir el resultado
print("Señal de entrada:")
print(x)
print("Filtro:")
print(h)
print("Señal convolucionada:")
print(y)


Señal de entrada:
[2 1 0 1 2]
Filtro:
[ 1 -1]
Señal convolucionada:
[-1 -1  1  1]


In [5]:
import numpy as np
from scipy.signal import convolve2d

# Definir la matriz de entrada (señal) y el Kernel
input_matrix = np.array([[1, 2, 3, 3],
                        [4, 5, 6, 6],
                        [7, 8, 9, 9],
                        [7, 8, 9, 9]])
kernel = np.array([[0, 1, 0],
                  [-1, 1, -1],
                  [0, 1, 0]])

In [6]:
# Realizar la convolución 2D
output_matrix = convolve2d(input_matrix, kernel, mode='valid')

# Imprimir el resultado
print("Señal de entrada:")
print(input_matrix)
print("kernel:")
print(kernel)
print("Señal convolucionada:")
print(output_matrix)


Señal de entrada:
[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]
 [7 8 9 9]]
kernel:
[[ 0  1  0]
 [-1  1 -1]
 [ 0  1  0]]
Señal convolucionada:
[[5 7]
 [5 7]]
